# server app port
server:
  port: 9092

# config mongodb server local
spring:
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest
    virtual_host: /
  data:
    mongodb:
      host: LocalHost
      port: 27017
      authentication-database: none
      database: Shopping
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka